# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Swift_Weibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'SnapKit'
pod 'Alamofire'
pod 'QorumLogs'

  # Pods for Swift_Weibo

end
